sudo: false
services:
  - docker

language: python

env:
  global:
    - DOCKER_IMAGE_NAME=alephdata/memorious

matrix:
  include:
    - python: "3.6"
      env: TOXENV=py36

install:
  - "sudo apt-get install p7zip-full libicu-dev"
  - "pip install -q tox twine pyicu"

script:
  - tox

after_success:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  # push tag as well
  - if [[ $TRAVIS_TAG = $TRAVIS_BRANCH ]]; then
      python setup.py sdist bdist_wheel ;
      twine upload dist/* ;
      docker build -t alephdata/memorious:latest . ;
      docker tag alephdata/memorious:latest alephdata/memorious:$TRAVIS_TAG ;
      docker push alephdata/memorious:$TRAVIS_TAG ;
      docker push alephdata/memorious:latest ;
    fi
